"""initial tables

Revision ID: 47df268b5396
Revises: 
Create Date: 2026-07-10 22:11:27.974395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47df268b5396'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('geographic_extent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('administrative_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_submission_count', sa.Integer(), nullable=False),
    sa.Column('trusted_demand', sa.Float(), nullable=False),
    sa.Column('suspicious_demand', sa.Float(), nullable=False),
    sa.Column('affected_population', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('persistence', sa.String(length=50), nullable=True),
    sa.Column('demand_velocity', sa.Float(), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('NEW', 'GROWING', 'STABLE', 'DECLINING', 'RESOLVED', 'CLOSED', name='clusterlifecyclestate'), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradictory_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_reported', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latest_report', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'MP', 'OFFICER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('CITIZEN_SUBMISSION', 'DEMOGRAPHIC', 'INFRASTRUCTURE', 'DEVELOPMENT_PLAN', 'PUBLIC_DATASET', 'GOVERNMENT_DATASET', 'HISTORICAL_RECORD', 'NEWS_ARTICLE', 'OFFICER_VERIFICATION', 'INDEPENDENT_EVIDENCE', name='evidencetype'), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieval_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('publication_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geographic_relevance', sa.Float(), nullable=True),
    sa.Column('temporal_relevance', sa.Float(), nullable=True),
    sa.Column('relationship_to_issue', sa.Enum('SUPPORTING', 'CONTRADICTING', 'NEUTRAL', 'UNVERIFIED', name='evidencerelationshiptype'), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'DEFERRED', name='prioritylevel'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bonuses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('penalties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'NORMALIZED', 'LOCATION_RESOLVED', 'UNDERSTOOD', 'NEEDS_CLARIFICATION', 'WAITING_FOR_CITIZEN', 'ASSESSED', 'AUTHENTICITY_SCORED', 'CLUSTERED', 'ENRICHED', 'PRIORITIZED', 'RECOMMENDED', 'READY_FOR_REVIEW', 'COMPLETED', 'PROCESSING_FAILED', 'NEEDS_REVIEW', 'REJECTED', 'ABANDONED', name='submissionstatus'), nullable=False),
    sa.Column('source_modality', sa.Enum('TEXT', 'VOICE', 'IMAGE', 'DOCUMENT', 'VIDEO', 'MESSAGING', name='sourcemodality'), nullable=False),
    sa.Column('source_channel', sa.String(length=50), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('normalized_content', sa.Text(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('response_language', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('affected_population', sa.Integer(), nullable=True),
    sa.Column('affected_households', sa.Integer(), nullable=True),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gps_permission_granted', sa.Boolean(), nullable=True),
    sa.Column('sender_latitude', sa.Float(), nullable=True),
    sa.Column('sender_longitude', sa.Float(), nullable=True),
    sa.Column('sender_gps_accuracy', sa.Float(), nullable=True),
    sa.Column('sender_gps_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authenticity_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('authenticity_score', sa.Float(), nullable=False),
    sa.Column('authenticity_status', sa.Enum('GENUINE', 'LIKELY_GENUINE', 'UNCERTAIN', 'SUSPICIOUS', 'LIKELY_FRAUDULENT', 'FRAUDULENT', name='authenticitystatus'), nullable=False),
    sa.Column('demand_weight', sa.Float(), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('calculation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('primary_issue', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_cause', sa.Text(), nullable=True),
    sa.Column('affected_infrastructure', sa.String(length=255), nullable=True),
    sa.Column('candidate_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issue_duration', sa.String(length=100), nullable=True),
    sa.Column('severity_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgency_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('people_affected', sa.Integer(), nullable=True),
    sa.Column('households_affected', sa.Integer(), nullable=True),
    sa.Column('vulnerable_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_impact', sa.Text(), nullable=True),
    sa.Column('safety_impact', sa.Text(), nullable=True),
    sa.Column('education_impact', sa.Text(), nullable=True),
    sa.Column('mobility_impact', sa.Text(), nullable=True),
    sa.Column('economic_impact', sa.Text(), nullable=True),
    sa.Column('environmental_impact', sa.Text(), nullable=True),
    sa.Column('service_disruption', sa.Text(), nullable=True),
    sa.Column('emergency_conditions', sa.Boolean(), nullable=True),
    sa.Column('alternatives_available', sa.Text(), nullable=True),
    sa.Column('requested_action', sa.Text(), nullable=True),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ambiguity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('alternative_interpretations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_inference_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'WAITING_FOR_CITIZEN', 'COMPLETED', 'ABANDONED', 'TIMED_OUT', name='conversationstate'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_routings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('primary_department', sa.String(length=255), nullable=False),
    sa.Column('alternative_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('routing_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jurisdiction_uncertainty', sa.Boolean(), nullable=False),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('routing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_evidence_id', sa.UUID(), nullable=False),
    sa.Column('target_evidence_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('SUPPORTING', 'CONTRADICTING', 'NEUTRAL', 'UNVERIFIED', name='evidencerelationshiptype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['context_evidence.id'], ),
    sa.ForeignKeyConstraint(['target_evidence_id'], ['context_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_cluster_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.String(length=500), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('ward', sa.String(length=255), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('GPS', 'MAP_PIN', 'TYPED_ADDRESS', 'SPOKEN_ADDRESS', 'EXTRACTED_TEXT', 'MEDIA_METADATA', 'OFFICER_VERIFICATION', name='locationsource'), nullable=False),
    sa.Column('precision', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('geocoding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officer_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REQUEST_INVESTIGATION', 'REQUEST_CLARIFICATION', 'ESCALATED', 'PENDING', name='reviewdecision'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_added', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_score_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Enum('POLITICAL_IMPACT', 'SOCIAL_IMPACT', 'CASTE_DYNAMICS', 'SCIENTIFIC_BASIS', 'NATURAL_RISK', 'ENVIRONMENTAL_IMPACT', 'INNOVATION_POTENTIAL', 'SOCIETAL_BENEFIT', 'HUMANITARIAN_CONCERN', 'MORAL_ETHICAL_WEIGHT', 'RELIGIOUS_SENSITIVITY', 'FINANCIAL_IMPACT', 'FUTURISTIC_LONGTERM', 'EDUCATIONAL_VALUE', 'HISTORICAL_SIGNIFICANCE', 'SENTIMENTAL_EMOTIONAL', 'ADMINISTRATIVE_RISK', 'PUBLIC_CRITICISM_RISK', 'LEGAL_COMPLIANCE_RISK', 'IMPLEMENTATION_RISK', name='threatdimension'), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['priority_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('priority_assessment_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('responsible_department_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('implementation_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_outcomes', sa.Text(), nullable=True),
    sa.Column('expected_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('supporting_evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradictory_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alternative_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ),
    sa.ForeignKeyConstraint(['priority_assessment_id'], ['priority_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authenticity_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('signal_name', sa.String(length=255), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['authenticity_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('sender_city', sa.String(length=255), nullable=True),
    sa.Column('sender_district', sa.String(length=255), nullable=True),
    sa.Column('sender_constituency', sa.String(length=255), nullable=True),
    sa.Column('issue_city', sa.String(length=255), nullable=True),
    sa.Column('issue_district', sa.String(length=255), nullable=True),
    sa.Column('issue_constituency', sa.String(length=255), nullable=True),
    sa.Column('city_match', sa.Boolean(), nullable=True),
    sa.Column('district_match', sa.Boolean(), nullable=True),
    sa.Column('constituency_match', sa.Boolean(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('verification_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_verifications')
    op.drop_table('conversation_messages')
    op.drop_table('authenticity_signals')
    op.drop_table('submission_media')
    op.drop_table('recommendations')
    op.drop_table('priority_score_components')
    op.drop_table('officer_reviews')
    op.drop_table('locations')
    op.drop_table('issue_cluster_memberships')
    op.drop_table('evidence_relationships')
    op.drop_table('department_routings')
    op.drop_table('conversation_sessions')
    op.drop_table('case_assessments')
    op.drop_table('authenticity_assessments')
    op.drop_table('submissions')
    op.drop_table('priority_assessments')
    op.drop_table('context_evidence')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('issue_clusters')
    # ### end Alembic commands ###
