"""add constituencies table

Revision ID: bfa4e93c9ef9
Revises: 47df268b5396
Create Date: 2026-07-11 01:56:34.138496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'bfa4e93c9ef9'
down_revision: Union[str, Sequence[str], None] = '47df268b5396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('ac_number', sa.String(length=50), nullable=True),
    sa.Column('pc_number', sa.String(length=50), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_constituencies_geom', 'constituencies', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_constituencies_district'), 'constituencies', ['district'], unique=False)
    op.create_index(op.f('ix_constituencies_name'), 'constituencies', ['name'], unique=False)
    op.create_index(op.f('ix_constituencies_state'), 'constituencies', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_constituencies_state'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_name'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_district'), table_name='constituencies')
    op.drop_index('idx_constituencies_geom', table_name='constituencies', postgresql_using='gist')
    op.drop_table('constituencies')
    # ### end Alembic commands ###
